/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_Alternating_1.h"
#include "PWM_Clock.h"
#include "PWM_Out_1_aliases.h"
#include "PWM_Out_1.h"
#include "Audible_Frequency.h"
#include "PWM_Alternating_2.h"
#include "Clock_Audible.h"
#include "PWM_Clock_2.h"
#include "pin_12kHz_aliases.h"
#include "pin_12kHz.h"
#include "PWM_Out_2_aliases.h"
#include "PWM_Out_2.h"
#include "PWM_Alternating_3.h"
#include "PWM_Out_3_aliases.h"
#include "PWM_Out_3.h"
#include "PWM_Clock_3.h"
#include "timer_clock_1.h"
#include "PWM_Alternating_Timer.h"
#include "isr_msec.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

